### PR TITLE
Update .travis.yml away from legacy infrastructure

### PR DESCRIPTION
**Pull request by JasonGross**
Following https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade.

Also add a cpanfile for cpan dependencies so the default install script of `cpanm --quiet --installdeps --notest .` Just Works.

### CODE REVIEW

**Comment by alexmv** [comment]
LGTM.

**Comment by alexmv** [comment]
Why does github show this as "The Travis CI build passed" if https://travis-ci.org/barnowl/barnowl/branches shows the branch as "Errored"?

**Comment by alexmv** [comment]
Actually, NAK: https://travis-ci.org/barnowl/barnowl/jobs/94099080#L86

libzephyr-dev doesn't get installed.

**Comment by andersk** [comment]
Not a regression, but

```
Warning: prerequisite Any::Moose 0.13 not found.
Warning: prerequisite AnyEvent::HTTP 0 not found.
Warning: prerequisite DateTime::Format::Strptime 1.4000 not found.
Warning: prerequisite Lingua::EN::Keywords 0 not found.
Warning: prerequisite MIME::Base64::URLSafe 0.01 not found.
Warning: prerequisite Ouch 0.0400 not found.
Warning: prerequisite URI::Encode 0.02 not found.
```

**Comment by JasonGross** [comment]
> Why does github show this as "The Travis CI build passed" if https://travis-ci.org/barnowl/barnowl/branches shows the branch as "Errored"?

Because I accidentally pushed this branch to barnowl/barnowl rather than JasonGross/barnowl, and then deleted it before travis ran.  You actually want to look at https://travis-ci.org/barnowl/barnowl/pull_requests.

**Comment by JasonGross** [comment]
> libzephyr-dev doesn't get installed

Oh, right.  I'm waiting on https://github.com/travis-ci/apt-package-whitelist/issues/1901; it'll probably be fixed within a few days.  I'll add a comment when that happens.

**Comment by JasonGross** [comment]
> ```
Warning: prerequisite Any::Moose 0.13 not found.
Warning: prerequisite AnyEvent::HTTP 0 not found.
Warning: prerequisite DateTime::Format::Strptime 1.4000 not found.
Warning: prerequisite Lingua::EN::Keywords 0 not found.
Warning: prerequisite MIME::Base64::URLSafe 0.01 not found.
Warning: prerequisite Ouch 0.0400 not found.
Warning: prerequisite URI::Encode 0.02 not found.
```
>
> (Not a regression, but should probably be fixed.)

Fixed

**Comment by JasonGross** [comment]
> libzephyr-dev doesn't get installed.

Now it does.  Does everything look good, now?

**Comment by JasonGross** [comment]
Bump
@alexmv @andersk, does this look good now?

**Comment by alexmv** [comment]
:shipit:

**Pull request merged**
